version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
